name: CI Frontend | Build & Teste

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
    types: [opened, edited, synchronize]

jobs:
  build_test_frontend:
    name: Build, Lint & Teste
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Código
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Instalar Dependências
        run: npm ci

      - name: Verificar Qualidade do Código (Linting)

        run: npm run lint


      - name: Fazer Build da Aplicação (Vite)
        run: npm run build

      - name: Rodar Testes Unitários

        run: npm run test


      - name: Publicar Relatório de Testes (JUnit XML)

        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-testes-frontend
          path: test-results.xml
